### ISSUE TITLE
multiple # 

### ISSUE THREAD

**Issue by RBdevelop** [ddrake/path-problem#1]
## How would you make this work for multiple # in the input file ?  example

```
    ........................
    ........................
    ....#...................
    ........................
    ........................
    ........................
    ........................
    ..................#.....
    ........................
    ........................
    ........................
    ........................
```

**Comment by ddrake** [comment]
It definitely does work for the example you mentioned.  Your example is actually the first test in the pather_spec.rb file which is included in the repository.  You can check it for yourself by cloning the repository, installing rspec if necessary and running the tests via: `rspec pather_spec.rb`   It should result in 14 examples, 0 failures.
